---
- name: change password linux
  hosts: all
  become: False
  gather_facts: no
  vars:
    myuser: "root"
    mypassword: "monogroup"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"
